build:
  version: 130.0.0
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/billingdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true