build:
  version: 130.0.0
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/billingdb
    username: postgres
    password: postgres
  bus:
    enabled: true
  kafka:
    bootstrap-servers: kafka:9092
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s    
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
      
      
    

    
