version: 3.0.0
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/catalog

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
