version: 3.0.0
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/catalog
  bus:
    enabled: false
  kafka:
    bootstrap-servers: kafka:9092  
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
