version: 3.0.0
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notification
  bus:
    enabled: true
  kafka:
    bootstrap-servers: kafka:9092 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/      

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"        
